### ISSUE TITLE
New variables for non carousel library display

### ISSUE THREAD

**Issue by Maxplosion** [CTalvio/Kaleidochromic#1]
Hi, thanks for your work! really like the new more colorful touch of kaleidochromic.

I'd have a question regarding variables, first of all, great idea using them!
Would it be possible to add a variable to trigger the Image Carousel for Libaries? 

I really don't like them being displayed as carousel on the start page and always disable it using
`@media all and (min-width: 50em) {
  .homePage .emby-scroller {
  }
    margin-right: 0;
  .homePage .emby-scrollbuttons {
    display: none;
  }
  .homePage .itemsContainer {
    flex-wrap: wrap;
  }
}`

It would be nice just to toggle this on and off if possible. 
Overall I'm always happy with more variables so I don't have to copy paste the source on every change, I like the @import quite a lot.

**Comment by CTalvio** [comment]
You don't need to to copy the whole thing to make changes. You can just make additional changes by adding your own code after the import line of the theme. This way you still get updates, and your own modifications gets applied on top of that.

Variables let you change a number used in multiple places with a single line, CSS is not really a programming language so it's very limited in terms of conditional triggers. Mostly you can just make it apply different code depending on the browsers rendering and viewport size.

**Comment by Maxplosion** [comment]
that is great to hear, did not know I could combine manual css with the import!
thanks!
