### ISSUE TITLE
Background not changing

### ISSUE THREAD

**Issue by Marios1231** [CTalvio/Kaleidochromic#10]
Hey i like this theme very much but I have some issues with it like the background doesn't change just stays on black
<img width="1095" alt="Screen Shot 2021-04-22 at 10 47 26 pm" src="https://user-images.githubusercontent.com/52550609/115716716-cdfcad80-a3bc-11eb-9548-791d90b16d6a.png">
and Also My folder don't look the same as yours 
<img width="448" alt="Screen Shot 2021-04-22 at 10 48 48 pm" src="https://user-images.githubusercontent.com/52550609/115716832-f2588a00-a3bc-11eb-9326-a497ffa47940.png">
And this is how your preview looks like

![111](https://user-images.githubusercontent.com/52550609/115716991-1f0ca180-a3bd-11eb-8949-e40850ef04ae.png)
as you can see not the same
please help, thank you.

**Comment by CTalvio** [comment]
You need to actually enable backdrops to have them. They are not a feature of the theme, rather my theme only changes how they look, when enabled.

User menu>Display>Backdrops
