### ISSUE TITLE
Backdrop not working with theme

### ISSUE THREAD

**Issue by Ishannaik** [CTalvio/Kaleidochromic#3]
![image](https://user-images.githubusercontent.com/11766476/100370036-ae3ea480-302b-11eb-8fc0-b96b560e9b55.png)
Just installed it and the backdrop is not there like in your screenshots

**Comment by CTalvio** [comment]
My screenshots are taken with the "Dark" theme as the base. The theme can be combined with any of the stock themes as the base, you are simply seeing what it looks like when purple haze is being used. The backdrops are still there, but purple hazes "backdrop overlay" makes theme very hard to see.

To get the same appearance as in the screenshots, please select the "Dark" theme in Display user settings.
