### ISSUE TITLE
Music album art does not have 'border-radius' applied.

### ISSUE THREAD

**Issue by CodeName393** [CTalvio/Kaleidochromic#4]
![image](https://user-images.githubusercontent.com/62503817/104543710-6f12f400-5669-11eb-9bac-993d56cb12e9.png)

```
.nowPlayingPageImage {
    display: block;
    bottom: 0;
    left: 0;
    right: 0;
    margin: 0 auto;
    width: 100%;
    box-shadow: 0 0 1.9vh #000;
    border: .1em solid #222;
    user-select: none;
    -moz-user-select: none;
    -webkit-user-drag: none;
    -webkit-user-select: none;
    -ms-user-select: none;
```

`border-radius: var(--rounding) !important;` is not applied to this part.
Ask for more!
If you add it, it looks like this.
![image](https://user-images.githubusercontent.com/62503817/104543836-bbf6ca80-5669-11eb-8c64-f50bda06980f.png)

**Comment by CTalvio** [comment]
Should be fixed. Give it a few minutes to apply.

Thanks for the report :D
