### ISSUE TITLE
New update breaks theme

### ISSUE THREAD

**Issue by Jinxyface** [CTalvio/Kaleidochromic#6]
Hello, recently updated do your latest version of the skin, but the accent color no longer applies, it's stuck at blue no matter what I do.

![image](https://user-images.githubusercontent.com/19889486/107133384-18d25300-68ad-11eb-8ae3-24f5c5b8a271.png)

**Comment by CTalvio** [comment]
That _IS_ the purple color.

And you are applying the same accent that Kaleidochromic already uses by default. That is why you are seeing no change.

Use the blue preset or set a custom color of your own, and you will see a difference.
