### ISSUE TITLE
No cards for users on the login page - JF 10.7

### ISSUE THREAD

**Issue by Arbitrate3280** [CTalvio/Kaleidochromic#8]
![Screenshot_20210309_152339](https://user-images.githubusercontent.com/26132870/110518887-75fb3780-80eb-11eb-88c4-a4b48ae2c91d.png)

In my opinion it looks weird without cards. 

Here's how it is in the default dark theme:
![Screenshot_20210309_152458](https://user-images.githubusercontent.com/26132870/110519021-9d520480-80eb-11eb-8f17-27d9068f6724.png)

**Comment by CTalvio** [comment]
Oh yeah, that is not intended. Will fix.

**Comment by CTalvio** [comment]
This should now be fixed.
